# Generated by Django 4.2 on 2026-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='cl',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='roll',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'cl'], name='idx_attendance_date_cl'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'cl', 'roll'], name='idx_attendance_date_cl_roll'),
        ),
    ]
